"""new User fields

Revision ID: 7d83b3a5e3a2
Revises: 55699fc03445
Create Date: 2025-05-14 10:40:04.098536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d83b3a5e3a2'
down_revision: Union[str, None] = '55699fc03445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sa.String(), nullable=True))
    op.create_foreign_key(op.f('fk_users_ava_id_media_files'), 'users', 'media_files', ['ava_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_ava_id_media_files'), 'users', type_='foreignkey')
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###
