"""naming convension

Revision ID: 990201af66fc
Revises: 7540ebcf27bb
Create Date: 2025-05-05 09:35:15.512924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '990201af66fc'
down_revision: Union[str, None] = '7540ebcf27bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_id', table_name='events')
    op.drop_index('ix_recipients_id', table_name='recipients')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')


    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_recipients_id', 'recipients', ['id'], unique=False)
    op.create_index('ix_events_id', 'events', ['id'], unique=False)
    # ### end Alembic commands ###
