"""global event validation

Revision ID: 7540ebcf27bb
Revises: aa359f3dc894
Create Date: 2025-05-03 21:12:12.107133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7540ebcf27bb'
down_revision: Union[str, None] = 'aa359f3dc894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_check_constraint(
        "chk_global_recipient_null",
        "events",
        "(NOT is_global) OR (recipient_id IS NULL)"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        "ck_events_global_recipient_null",
        "events"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
